### PR TITLE
Added wrapper for mono.

### PR DESCRIPTION
**Pull request by michael-emmi**

### CODE REVIEW

**Comment by zvonimir** [comment]
@shazqadeer : Maybe you could merge this for us?
I don't have write privileges on this repo. Maybe it would make sense that you make @michael-emmi and myself Owners of the `boogie-org` organization?
That way we would have write access to all repos in that org. Thanks!

**Comment by zvonimir** [comment]
Also see issue #36.

**Comment by ccadar** [comment]
@zvonimir I agree it would make sense for the two of you to have write access if you're interested in Boogie.  But my suggestion is to make TravisCI checks mandatory, and not merge PRs where the CI fails, like this one.

**Comment by zvonimir** [comment]
I agree. This requires updating/fixing CI travis script first. I am pretty sure CI is failing since the script/setup got deprecated.

**Comment by ccadar** [comment]
@michael-emmi Please rebase this so that the CI passes.

**Comment by ccadar** [comment]
@michael-emmi BTW, don't just set the build mode to Debug.  Try something like `BUILD_TYPE=${BUILD_TYPE:-Debug}` (set to Debug if not already set)

**Comment by michael-emmi** [comment]
@ccadar updated and rebased.

**Comment by ccadar** [comment]
Thanks!

**Pull request merged**
